export const USERS = [
  { name: "Kemal Erdem", nick: "Erdemli", avatar: "https://i.pravatar.cc/80?img=11" },
  { name: "Ayşe Demir", nick: "sunnyrose", avatar: "https://i.pravatar.cc/80?img=39" },
  { name: "Elif Yılmaz", nick: "Daenerys12", avatar: "https://i.pravatar.cc/80?img=49" },
  { name: "Zeynep Şahin", nick: "Rhaenyra", avatar: "https://i.pravatar.cc/80?img=19" },
  { name: "Hamza", nick: "cay", avatar: "https://i.pravatar.cc/80?img=15" },
  { name: "Mert Kaya", nick: "mertk", avatar: "https://i.pravatar.cc/80?img=33" },
  { name: "Selin Arslan", nick: "selinars", avatar: "https://i.pravatar.cc/80?img=28" },
  { name: "Bora Yıldız", nick: "boray", avatar: "https://i.pravatar.cc/80?img=7" },
];

export const INITIAL_TWITS = [
  {
    id: 101,
    userNick: "Erdemli",
    content: "Yürüyüş yapmak gerçekten rahatlatıcı. Her gün yapmaya karar verdim.",
    likeCount: 18,
    replyCount: 2,
    daysAgo: 1,
  },
  {
    id: 102,
    userNick: "Erdemli",
    content: "Bugün 10k adım. İyi geldi.",
    likeCount: 6,
    replyCount: 0,
    daysAgo: 3,
  },
  {
    id: 201,
    userNick: "sunnyrose",
    content: "Hafıza geliştirme kursuna yazıldım. Nerede olduğunu hatırlamıyorum.",
    likeCount: 220,
    replyCount: 6,
    daysAgo: 2,
  },
  {
    id: 202,
    userNick: "sunnyrose",
    content: "Kahve + kitap = günün en iyi kombosu.",
    likeCount: 52,
    replyCount: 1,
    daysAgo: 4,
  },
  {
    id: 301,
    userNick: "Daenerys12",
    content: "Bugün işlerim çok yoğundu. Ama yine de keyif aldım.",
    likeCount: 25,
    replyCount: 18,
    daysAgo: 6,
  },
  {
    id: 302,
    userNick: "Daenerys12",
    content: "Dizi önerisi: Succession baya sardı.",
    likeCount: 40,
    replyCount: 3,
    daysAgo: 7,
  },
  {
    id: 401,
    userNick: "Rhaenyra",
    content: "Yeni bir dil öğrenmeye başladım. Zor ama bir o kadar eğlenceli.",
    likeCount: 112,
    replyCount: 1,
    daysAgo: 9,
  },
  {
    id: 402,
    userNick: "Rhaenyra",
    content: "Bugün 30dk spor + 20dk yürüyüş.",
    likeCount: 19,
    replyCount: 0,
    daysAgo: 10,
  },
  {
    id: 501,
    userNick: "cay",
    content: "Merhaba",
    likeCount: 0,
    replyCount: 0,
    daysAgo: 0,
  },
  {
    id: 502,
    userNick: "cay",
    content: "Çok iyi",
    likeCount: 0,
    replyCount: 0,
    daysAgo: 0,
  },
  {
    id: 601,
    userNick: "mertk",
    content: "Frontend ödevi bitsin, rahatlayacağım.",
    likeCount: 7,
    replyCount: 2,
    daysAgo: 1,
  },
  {
    id: 602,
    userNick: "mertk",
    content: "Bugün Tailwind deniyorum.",
    likeCount: 9,
    replyCount: 1,
    daysAgo: 2,
  },
  {
    id: 701,
    userNick: "selinars",
    content: "Yeni playlist yaptım, efsane oldu.",
    likeCount: 14,
    replyCount: 2,
    daysAgo: 3,
  },
  {
    id: 702,
    userNick: "selinars",
    content: "Kedim klavyeye yatınca çalışma bitiyor 😄",
    likeCount: 33,
    replyCount: 5,
    daysAgo: 5,
  },
  {
    id: 801,
    userNick: "boray",
    content: "Bugün hava tam yürüyüşlük.",
    likeCount: 4,
    replyCount: 0,
    daysAgo: 1,
  },
  {
    id: 802,
    userNick: "boray",
    content: "React Router v6 mantığını nihayet oturttum.",
    likeCount: 11,
    replyCount: 2,
    daysAgo: 2,
  },
];
